### ISSUE TITLE
Can the prose classes be loaded from a CDN?

### ISSUE THREAD

**Issue by elimintz** [tailwindcss/typography#19] opened 2020-07-15 13:50 UTC
I understand that the recommended use is installation using npm. My specific use is in developing the Python framework [JustPy](https://justpy.io) that uses tailwind and for which installation from npm is not possible.

Any suggestion would be appreciated.

**Comment by adamwathan** [comment] 2020-07-15 14:42
Duplicate of https://github.com/tailwindcss/typography/issues/10

**Closed by adamwathan** 2020-07-15 14:42 UTC

**Comment by elimintz** [comment] 2020-07-15 14:46
Thank you!

**Comment by HugoDF** [comment] 2020-07-15 14:51
@adamwathan would you be interested in a PR to add the CDN instructions in the README?

**Comment by adamwathan** [comment] 2020-07-15 15:09
Definitely!
