### ISSUE TITLE
How to remove backquote around inline code?

### ISSUE THREAD

**Issue by dpyzo0o** [tailwindcss/typography#18] opened 2020-07-15 07:30 UTC
The default style of inline code has backquotes which I do not want. I tried to override it with the following configuration but it does not work.

```js
// tailwind.config.js
module.exports = {
  theme: {
    typography: {
      default: {
        css: {
          code: {
            '&::before': {
              content: '""',
            },
            '&::after': {
              content: '""',
            },
          }
          // ...
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    // ...
  ],
}
```

<img width="202" alt="Screen Shot 2020-07-15 at 15 28 55" src="https://user-images.githubusercontent.com/24768249/87516461-05149480-c6b0-11ea-9f25-eeed0f71fe56.png">

**Comment by adamwathan** [comment] 2020-07-15 15:13
Can you create a GitHub repo that reproduces this? I just tried it on our blog and was able to override it no problem with your exact code.

**Comment by ahaseeb04** [comment] 2020-07-15 18:41
I think exiting out from `npm run dev` and restarting the script should solve this issue.

**Comment by vincentdoerig** [comment] 2020-07-15 20:33
Hi @dpyzo0o, if you add `!important` it should work. So like this:
```js
typography: {
  default: {
    css: {
      code: {
        '&::before': {
          content: '"" !important',
        },
        '&::after': {
          content: '"" !important',
        },
      }
      // ...
    },
  },
},
```
I was able to reproduce your issue though, I think the problem is that the new class gets added _before_ the typography plugin class and thus overwriting it. 

![Screenshot 2020-07-15 at 22 31 25](https://user-images.githubusercontent.com/24668338/87592915-ee3f6380-c6ea-11ea-8fb0-b8b7d0dd149a.jpg)
I imagine this is something that could be fixed?

**Comment by dpyzo0o** [comment] 2020-07-16 03:06
@vincentdoerig Yes, adding `!important` can solve the issue but I'm trying to avoid using `!important` if possible. Indeed I'm able to remove the backquotes by setting `display: none`

```js
// tailwind.config.js
module.exports = {
  theme: {
    typography: {
      default: {
        css: {
          code: {
            '&::before': {
              display: 'none',
            },
            '&::after': {
              display: 'none',
            },
          }
          // ...
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    // ...
  ],
}
```

@adamwathan I'm sure this issue is reproducible, here is a minimal repo that reproduces the issue, https://github.com/dpyzo0o/tailwindcss-bug-reproduce

**Comment by dpyzo0o** [comment] 2020-07-16 03:22
@adamwathan some findings... Writing in this way will correctly overwrite the original style. Seems like using `&::before, &::after` will cause the styles to be applied before the original styles.

```js
// tailwind.config.js
module.exports = {
  theme: {
    typography: {
      default: {
        css: {
          'code::before': {
            content: '""',
          },
          'code::after': {
            content: '""',
          }
          // ...
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    // ...
  ],
}
```

**Comment by adamwathan** [comment] 2020-07-16 11:44
Ah yeah you know what I think I wrote it that way when I was testing things out, so I was wrong when I said I used your code exactly 🤦 

It looks like this is due to a particular detail of how deep merging works in lodash, which causes object properties to be merged in a different order than I'd expect (overrides are added as _earlier_ keys in the object being merged to, not later).

For now I would recommend mimicking the exact selector we use in the `styles.js` reference whenever you need to make an override, and we will see about making the merging behavior more intuitive.

**Comment by adamwathan** [comment] 2020-07-16 11:52
Actually I know exactly what is happening now, sorry.

Your changes are being merged with our existing `code` key, which comes before our `code::before` and `code::after` keys.

Here's our code:

```
code: {
  color: defaultTheme.colors.gray[900],
  fontWeight: '600',
},
'code::before': {
  content: '"`"',
},
'code::after': {
  content: '"`"',
},
```

When you're code is merged in, it creates this object:

```
code: {
  color: defaultTheme.colors.gray[900],
  fontWeight: '600',
  '&::before': {
    content: '""',
  },
  '&::after': {
    content: '""',
  },
},
'code::before': {
  content: '"`"',
},
'code::after': {
  content: '"`"',
},
```

So when it's all flattened out, our existing `code::before` and `code::after` selectors win. This is sort of a tough one to figure out how to "fix" because the current behavior is actually really useful for lots of situations, so we might just want to figure out a way to let the user control this more finely.

Going to close this for now since there's a solution (use our keys) and I can't say for sure we are going to take action on it.

**Closed by adamwathan** 2020-07-16 11:52 UTC

**Comment by neildobson-au** [comment] 2020-07-28 00:11
Hello, we have the same problem in that all our inline code is showing backticks, which we don't want. You mentioned that you have a solution: use our keys. Please can you explain this? I've gone through all the above and we still see backticks everywhere.

**Comment by neildobson-au** [comment] 2020-07-28 00:31
Apologies, I made a mistake in the `tailwind.config.js`. This is working for me now:

``` javascript
// tailwind.config.js
module.exports = {
  theme: {
    typography: {
      default: {
        css: {
          'code::before': {
            content: '""',
          },
          'code::after': {
            content: '""',
          },
        },
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
```

**Comment by alexellis** [comment] 2020-10-20 22:35
@Waterdrips ☝️ this should do the trick?

**Comment by MoSattler** [comment] 2020-11-24 15:24
Does not work for me - when I add this to my tailwind config, it completely breaks all styles. I am using 2.0.

**Comment by KushibikiMashu** [comment] 2022-01-22 03:00
For v3, this works for me.

https://github.com/tailwindlabs/tailwindcss-typography/issues/135#issuecomment-991251524

**Comment by almai** [comment] 2022-10-17 12:41
I know, I'm a little bit late to the party. But in case someone is interested in this. You can suppress the backticks with `prose-code:before:hidden prose-code:after:hidden`

**Comment by peterhijma** [comment] 2022-11-15 13:51
> I know, I'm a little bit late to the party. But in case someone is interested in this. You can suppress the backticks with `prose-code:before:hidden prose-code:after:hidden`

But not **too** late! Thanks!

**Comment by steven-tey** [comment] 2023-05-02 16:04
> I know, I'm a little bit late to the party. But in case someone is interested in this. You can suppress the backticks with `prose-code:before:hidden prose-code:after:hidden`

This did the trick! Thank you!

**Comment by JosiahParry** [comment] 2024-05-25 21:42
> prose-code:before:hidden prose-code:after:hidden

This worked! Thank you so much!!!!

**Comment by LamNguyenz** [comment] 2025-01-01 07:53
> I know, I'm a little bit late to the party. But in case someone is interested in this. You can suppress the backticks with `prose-code:before:hidden prose-code:after:hidden`

Thanks, you save my life

**Comment by sergiodantasz** [comment] 2025-02-23 22:36
Perfect, @kerryj89. I'm using v4 too, it worked well.

**Comment by tushgaurav** [comment] 2026-02-21 17:30
> These classes didn't work for me in v4. Here is what I used instead to kill it from the root:
> 
> @utility prose {
>   code {
>     &::before,
>     &::after {
>       content: none;
>     }
>   }
> }

Thank you so much man!
